#!/usr/bin/env bash
# 安装《创世》资源 profile。--print 可在任意平台审阅；--install 仅 Linux root。
set -euo pipefail

usage() {
  echo "用法: $0 --print|--install 2c2g|4c4g" >&2
  exit 2
}

MODE="${1:-}"; PROFILE="${2:-}"
case "$MODE" in --print|--install) ;; *) usage ;; esac

case "$PROFILE" in
  2c2g)
    NODE_MEMORY_HIGH=1024M
    NODE_MEMORY_MAX=1280M
    NODE_OLD_SPACE_MB=896
    DATABASE_POOL_MAX=5
    POSTGRES_SHARED_BUFFERS=256MB
    POSTGRES_MAX_CONNECTIONS=20
    ;;
  4c4g)
    NODE_MEMORY_HIGH=2304M
    NODE_MEMORY_MAX=2867M
    NODE_OLD_SPACE_MB=2048
    DATABASE_POOL_MAX=10
    POSTGRES_SHARED_BUFFERS=512MB
    POSTGRES_MAX_CONNECTIONS=40
    ;;
  *)
    echo "ERROR: profile 只能是 2c2g 或 4c4g" >&2
    exit 2
    ;;
esac

print_profile() {
  cat <<EOF
GENESIS_PROFILE=$PROFILE
NODE_MEMORY_HIGH=$NODE_MEMORY_HIGH
NODE_MEMORY_MAX=$NODE_MEMORY_MAX
NODE_OLD_SPACE_MB=$NODE_OLD_SPACE_MB
DATABASE_POOL_MAX=$DATABASE_POOL_MAX
POSTGRES_SHARED_BUFFERS=$POSTGRES_SHARED_BUFFERS
POSTGRES_MAX_CONNECTIONS=$POSTGRES_MAX_CONNECTIONS
EOF
}

if [[ "$MODE" == "--print" ]]; then
  print_profile
  exit 0
fi

[[ "$(uname -s)" == "Linux" ]] || { echo "ERROR: --install 仅支持 Linux" >&2; exit 1; }
[[ "${EUID:-$(id -u)}" -eq 0 ]] || { echo "ERROR: --install 必须以 root 运行" >&2; exit 1; }

install -d -m 0750 -o root -g genesis /etc/genesis
install -d -m 0755 /etc/systemd/system/genesis.service.d

PROFILE_ENV="$(mktemp)"
DROP_IN="$(mktemp)"
cleanup() { rm -f "$PROFILE_ENV" "$DROP_IN"; }
trap cleanup EXIT

cat >"$PROFILE_ENV" <<EOF
GENESIS_PROFILE=$PROFILE
DATABASE_POOL_MAX=$DATABASE_POOL_MAX
NODE_OPTIONS=--max-old-space-size=$NODE_OLD_SPACE_MB
EOF
install -m 0640 -o root -g genesis "$PROFILE_ENV" /etc/genesis/profile.env

cat >"$DROP_IN" <<EOF
[Service]
MemoryHigh=$NODE_MEMORY_HIGH
MemoryMax=$NODE_MEMORY_MAX
EOF
install -m 0644 "$DROP_IN" /etc/systemd/system/genesis.service.d/profile.conf

# 旧版 profile 曾安装生成连接上限；新版明确不限制正常生成并发。
rm -f /etc/nginx/snippets/genesis-generation.conf

found_pg=0
for conf_dir in /etc/postgresql/*/main/conf.d; do
  [[ -d "$conf_dir" ]] || continue
  found_pg=1
  cat >"$conf_dir/99-genesis-profile.conf" <<EOF
# generated by deploy/install-profile.sh ($PROFILE)
shared_buffers = '$POSTGRES_SHARED_BUFFERS'
max_connections = $POSTGRES_MAX_CONNECTIONS
listen_addresses = '127.0.0.1,::1'
EOF
  chmod 0644 "$conf_dir/99-genesis-profile.conf"
done
[[ "$found_pg" -eq 1 ]] || echo "WARN: 未发现 PostgreSQL conf.d；安装后重新运行" >&2

systemctl daemon-reload
echo "OK: installed profile $PROFILE"
print_profile
